[build]
#target = "x86_64-pc-windows-gnu"
#target = "x86_64-unknown-linux-gnu"
#target = "armv7-unknown-linux-gnueabihf"

[target.x86_64-unknown-linux-gnu]
linker = "x86_64-linux-gnu-gcc"

[target.armv7-unknown-linux-gnueabihf]
linker = "arm-linux-gnueabihf-gcc"